### PR TITLE
Fixed floating pinpoints and apk issues

### LINKED ISSUE #1: As a user, I want to open up the map, so that I can see all the available conferences next to me.
- [x] Open main menu after open map
- [x] Button to acess world map
- [x] Visualize world map
- [x] Button to go back to the main menu

### PR DESCRIPTION
**Pull request by samyuh**
- Apk now display the map correctly.
- Now pinpoints are anchored to one position.

### CODE REVIEW

**Review by samyuh — COMMENTED** [review]
Alteration on AndroidManifest needed to use internet on APK.
All other alterations related to pinpoint.

**Comment by Calmskyy** [comment]
Bugs appear fixed, approved

**Review by Hugomguima — CHANGES_REQUESTED** [review]
All icons are Computer Science.
Otherrwise everything is ok.

**Review by Calmskyy — APPROVED** [review]

**Comment by samyuh** [comment]
> All icons are Computer Science.
> Otherrwise everything is ok.

Fixed that on this newer [commit](https://github.com/FEUP-ESOF-2020-21/open-cx-t2g1-2b-2b/pull/3/commits/bed3084249cf34c92f86798bbae9878909fac68f)! :)

**Review by Hugomguima — APPROVED** [review]
Changes approved

**Pull request merged**
