### PR TITLE
Now users can save conferences

### LINKED ISSUE #14: As a user, I want to save a conference I wish to attend, so that I can mark it (save) on the map for easy access.

### PR DESCRIPTION
**Pull request by samyuh**
- [x] Users can press save to save a conference when they open details
- [x] Saved conferences are saved locally
- [x] Changed colors

### CODE REVIEW

**Comment by Calmskyy** [comment]
Tested and functionality seems working fine. However, when checking a conference's details, I think the black text does not go well with the new purple color, the text should have more contrast with the background to be more easily readable.

**Review by Hugomguima — APPROVED** [review]
Changes approved

**Review by samyuh — COMMENTED** [review]
Everything looking fine, jsut need to fix conference details

**Review by BernardoFerreira00 — APPROVED** [review]

**Review by Calmskyy — APPROVED** [review]
The text has been fixed and looks good now, approved

**Pull request merged**
